# Generated by Django 5.1.5 on 2025-02-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resume',
            field=models.CharField(blank=True, help_text='Résumé du projet', max_length=350, null=True),
        ),
    ]
