# Generated by Django 5.1.5 on 2025-04-19 15:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
    ]
