# Generated by Django 5.1.5 on 2025-02-18 15:39

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Your bio', null=True)),
                ('experience', models.TextField(blank=True, help_text='Your professional experience')),
                ('skills', models.TextField(blank=True, help_text='Your skills')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('github', models.URLField(blank=True, help_text='Your GitHub profile', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Your LinkedIn profile', null=True)),
                ('website', models.URLField(blank=True, help_text='Your personal website', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
