# Generated by Django 5.1.5 on 2025-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='short_bio',
            field=models.CharField(blank=True, help_text='Your short bio for the template profile', max_length=400, null=True),
        ),
    ]
