# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Keep Render App Alive

on:
  schedule:
    - cron: '*/10 * * * *' # Exécute toutes les 10 minutes

jobs:
  ping_render:
    runs-on: ubuntu-latest  # Correction du nom pour garder la cohérence avec le nom de l'OS
    steps:
      - name: Ping Render App
        run: curl -s -o /dev/null -w "%{http_code}" https://hericldev.onrender.com && echo "Ping réussi"
